services:
  - type: web
    name: sentiment
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt && python -m nltk.downloader stopwords
    startCommand: python -m gunicorn main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9 # <-- Isko 3.11.9 karein
