services:
  - type: web
    name: sentiment
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python -m gunicorn main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0

